### ISSUE TITLE
[FEAT] 기존파일 1뷰컨 1스토리보드로 분리

### ISSUE THREAD

**Issue by mini-min** [mini-min/KkoKkioTalk-Clone-iOS#1]
# 👀 이슈 (issue)

지난 솝트 과제에서 수행했던 카카오톡 클론코딩 프로젝트를 사용할 수 있도록 정리하는 이슈입니다.

# 🚀 to-do

- [x] 로그인뷰 스토리보드 분리
- [x] 회원가입 뷰 스토리보드 분리
- [x] 친구 뷰 스토리보드 분리
- [x] 프로필 뷰 스토리보드 분리
- [x] 채팅 뷰 스토리보드 분리
- [x] 검색 뷰 스토리보드 분리
- [x] 쇼핑 뷰 스토리보드 분리
- [x] 더보기 뷰 스토리보드 분리
